export const INCREASE_PRODUCT_COUNT = "INCREASE_PRODUCT_COUNT";
export const DECREASE_PRODUCT_COUNT = "DECREASE_PRODUCT_COUNT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const RESET_PRODUCT_DATA = "RESET_PRODUCT_DATA";
